# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliTest < Formula
  desc "A test CLI built by JP"
  homepage "https://github.com/joaopalet/cli-test"
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joaopalet/cli-test/releases/download/v0.0.3/cli-test_Darwin_x86_64.tar.gz"
      sha256 "ecf7f9693c0f218c92d9c07bda921f37044d7f290b859d25940dd244f28726d0"

      def install
        bin.install "jp-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joaopalet/cli-test/releases/download/v0.0.3/cli-test_Darwin_arm64.tar.gz"
      sha256 "4a35cb12bcc33afbf9f5df7d811bec3ab7c8e4dd4025b52525866c838cc65d6d"

      def install
        bin.install "jp-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaopalet/cli-test/releases/download/v0.0.3/cli-test_Linux_arm64.tar.gz"
      sha256 "091fef4a463ddac4afd26a745f155333d0f32fc1e932ee7163e5b0f7f999680a"

      def install
        bin.install "jp-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joaopalet/cli-test/releases/download/v0.0.3/cli-test_Linux_x86_64.tar.gz"
      sha256 "5a2226da94b457224dfa0ec676dedabc14df3a5c152a01bf79c1076e906ef195"

      def install
        bin.install "jp-cli"
      end
    end
  end
end
