# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JpCli < Formula
  desc "A test CLI built by JP"
  homepage "https://github.com/joaopalet/cli-test"
  version "0.0.16"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joaopalet/jp-cli/releases/download/v0.0.16/jp-cli_Darwin_x86_64.tar.gz"
      sha256 "7b76d11c5c60078fa83a5e34c7f2338fa4215788dec8c25519aedea771c7884f"

      def install
        bin.install "jp-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joaopalet/jp-cli/releases/download/v0.0.16/jp-cli_Darwin_arm64.tar.gz"
      sha256 "0da8ec60d0230afff4ee0935211bbe8b6b1ed64eaa976d45e69d902446169d11"

      def install
        bin.install "jp-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaopalet/jp-cli/releases/download/v0.0.16/jp-cli_Linux_arm64.tar.gz"
      sha256 "a81c69972142728d84554b55f372024666558d441e066a681d11a09c26eab378"

      def install
        bin.install "jp-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joaopalet/jp-cli/releases/download/v0.0.16/jp-cli_Linux_x86_64.tar.gz"
      sha256 "462493f5cfb5dcd387080817d06d50f2a8e6a802eef3a245d7e5e2a410881dee"

      def install
        bin.install "jp-cli"
      end
    end
  end
end
