# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JpCli < Formula
  desc "A test CLI built by JP"
  homepage "https://github.com/joaopalet/cli-test"
  version "0.0.18"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joaopalet/jp-cli/releases/download/v0.0.18/jp-cli_Darwin_x86_64.tar.gz"
      sha256 "daaba4c6f7fd8e469b7ab20dd6142994e5bc5a9a242d55965796e2335a7b4160"

      def install
        bin.install "jp-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joaopalet/jp-cli/releases/download/v0.0.18/jp-cli_Darwin_arm64.tar.gz"
      sha256 "fa171b6d6d57f803e3d2956a0efdaa383d3d82ce9bb5973cf6a27d93e3020322"

      def install
        bin.install "jp-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joaopalet/jp-cli/releases/download/v0.0.18/jp-cli_Linux_arm64.tar.gz"
      sha256 "9099b41c3d5fd154b06907a1fab8ae04b98791150b5e145972fdc0fe5fd10469"

      def install
        bin.install "jp-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joaopalet/jp-cli/releases/download/v0.0.18/jp-cli_Linux_x86_64.tar.gz"
      sha256 "6a698499522d3dd03d5b99804aab59da5616a69faf5989b53e9712662eed4089"

      def install
        bin.install "jp-cli"
      end
    end
  end
end
